#include "asciimap.h"

const ASCIIMAP asciimap_us[ASCIIMAP_SIZE] = {
    {0, 0},             /* NUL */
    {0, 0},             /* SOH */
    {0, 0},             /* STX */
    {0, 0},             /* ETX */
    {0, 0},             /* EOT */
    {0, 0},             /* ENQ */
    {0, 0},             /* ACK */
    {0, 0},             /* BEL */
    {0x2a, 0},          /* BS  */  /* Keyboard Delete (Backspace) */
    {0x2b, 0},          /* TAB */  /* Keyboard Tab */
    {0x28, 0},          /* LF  */  /* Keyboard Return (Enter) */
    {0, 0},             /* VT  */
    {0, 0},             /* FF  */
    {0, 0},             /* CR  */
    {0, 0},             /* SO  */
    {0, 0},             /* SI  */
    {0, 0},             /* DLE */
    {0, 0},             /* DC1 */
    {0, 0},             /* DC2 */
    {0, 0},             /* DC3 */
    {0, 0},             /* DC4 */
    {0, 0},             /* NAK */
    {0, 0},             /* SYN */
    {0, 0},             /* ETB */
    {0, 0},             /* CAN */
    {0, 0},             /* EM  */
    {0, 0},             /* SUB */
    {0, 0},             /* ESC */
    {0, 0},             /* FS  */
    {0, 0},             /* GS  */
    {0, 0},             /* RS  */
    {0, 0},             /* US  */
    {0x2c, 0},          /*   */
    {0x1e, ASCIIMAP_MODIFIER_SHIFT},      /* ! */
    {0x34, ASCIIMAP_MODIFIER_SHIFT},      /* " */
    {0x20, ASCIIMAP_MODIFIER_SHIFT},      /* # */
    {0x21, ASCIIMAP_MODIFIER_SHIFT},      /* $ */
    {0x22, ASCIIMAP_MODIFIER_SHIFT},      /* % */
    {0x24, ASCIIMAP_MODIFIER_SHIFT},      /* & */
    {0x34, 0},          /* ' */
    {0x26, ASCIIMAP_MODIFIER_SHIFT},      /* ( */
    {0x27, ASCIIMAP_MODIFIER_SHIFT},      /* ) */
    {0x25, ASCIIMAP_MODIFIER_SHIFT},      /* * */
    {0x2e, ASCIIMAP_MODIFIER_SHIFT},      /* + */
    {0x36, 0},          /* , */
    {0x2d, 0},          /* - */
    {0x37, 0},          /* . */
    {0x38, 0},          /* / */
    {0x27, 0},          /* 0 */
    {0x1e, 0},          /* 1 */
    {0x1f, 0},          /* 2 */
    {0x20, 0},          /* 3 */
    {0x21, 0},          /* 4 */
    {0x22, 0},          /* 5 */
    {0x23, 0},          /* 6 */
    {0x24, 0},          /* 7 */
    {0x25, 0},          /* 8 */
    {0x26, 0},          /* 9 */
    {0x33, ASCIIMAP_MODIFIER_SHIFT},      /* : */
    {0x33, 0},          /* ; */
    {0x36, ASCIIMAP_MODIFIER_SHIFT},      /* < */
    {0x2e, 0},          /* = */
    {0x37, ASCIIMAP_MODIFIER_SHIFT},      /* > */
    {0x38, ASCIIMAP_MODIFIER_SHIFT},      /* ? */
    {0x1f, ASCIIMAP_MODIFIER_SHIFT},      /* @ */
    {0x04, ASCIIMAP_MODIFIER_SHIFT},      /* A */
    {0x05, ASCIIMAP_MODIFIER_SHIFT},      /* B */
    {0x06, ASCIIMAP_MODIFIER_SHIFT},      /* C */
    {0x07, ASCIIMAP_MODIFIER_SHIFT},      /* D */
    {0x08, ASCIIMAP_MODIFIER_SHIFT},      /* E */
    {0x09, ASCIIMAP_MODIFIER_SHIFT},      /* F */
    {0x0a, ASCIIMAP_MODIFIER_SHIFT},      /* G */
    {0x0b, ASCIIMAP_MODIFIER_SHIFT},      /* H */
    {0x0c, ASCIIMAP_MODIFIER_SHIFT},      /* I */
    {0x0d, ASCIIMAP_MODIFIER_SHIFT},      /* J */
    {0x0e, ASCIIMAP_MODIFIER_SHIFT},      /* K */
    {0x0f, ASCIIMAP_MODIFIER_SHIFT},      /* L */
    {0x10, ASCIIMAP_MODIFIER_SHIFT},      /* M */
    {0x11, ASCIIMAP_MODIFIER_SHIFT},      /* N */
    {0x12, ASCIIMAP_MODIFIER_SHIFT},      /* O */
    {0x13, ASCIIMAP_MODIFIER_SHIFT},      /* P */
    {0x14, ASCIIMAP_MODIFIER_SHIFT},      /* Q */
    {0x15, ASCIIMAP_MODIFIER_SHIFT},      /* R */
    {0x16, ASCIIMAP_MODIFIER_SHIFT},      /* S */
    {0x17, ASCIIMAP_MODIFIER_SHIFT},      /* T */
    {0x18, ASCIIMAP_MODIFIER_SHIFT},      /* U */
    {0x19, ASCIIMAP_MODIFIER_SHIFT},      /* V */
    {0x1a, ASCIIMAP_MODIFIER_SHIFT},      /* W */
    {0x1b, ASCIIMAP_MODIFIER_SHIFT},      /* X */
    {0x1c, ASCIIMAP_MODIFIER_SHIFT},      /* Y */
    {0x1d, ASCIIMAP_MODIFIER_SHIFT},      /* Z */
    {0x2f, 0},          /* [ */
    {0x31, 0},          /* \ */
    {0x30, 0},          /* ] */
    {0x23, ASCIIMAP_MODIFIER_SHIFT},      /* ^ */
    {0x2d, ASCIIMAP_MODIFIER_SHIFT},      /* _ */
    {0x35, 0},          /* ` */
    {0x04, 0},          /* a */
    {0x05, 0},          /* b */
    {0x06, 0},          /* c */
    {0x07, 0},          /* d */
    {0x08, 0},          /* e */
    {0x09, 0},          /* f */
    {0x0a, 0},          /* g */
    {0x0b, 0},          /* h */
    {0x0c, 0},          /* i */
    {0x0d, 0},          /* j */
    {0x0e, 0},          /* k */
    {0x0f, 0},          /* l */
    {0x10, 0},          /* m */
    {0x11, 0},          /* n */
    {0x12, 0},          /* o */
    {0x13, 0},          /* p */
    {0x14, 0},          /* q */
    {0x15, 0},          /* r */
    {0x16, 0},          /* s */
    {0x17, 0},          /* t */
    {0x18, 0},          /* u */
    {0x19, 0},          /* v */
    {0x1a, 0},          /* w */
    {0x1b, 0},          /* x */
    {0x1c, 0},          /* y */
    {0x1d, 0},          /* z */
    {0x2f, ASCIIMAP_MODIFIER_SHIFT},      /* { */
    {0x31, ASCIIMAP_MODIFIER_SHIFT},      /* | */
    {0x30, ASCIIMAP_MODIFIER_SHIFT},      /* } */
    {0x35, ASCIIMAP_MODIFIER_SHIFT},      /* ~ */
};

const ASCIIMAP asciimap_jp[ASCIIMAP_SIZE] = {
    {0, 0},             /* NUL */
    {0, 0},             /* SOH */
    {0, 0},             /* STX */
    {0, 0},             /* ETX */
    {0, 0},             /* EOT */
    {0, 0},             /* ENQ */
    {0, 0},             /* ACK */
    {0, 0},             /* BEL */
    {0x2a, 0},          /* BS  */  /* Keyboard Delete (Backspace) */
    {0x2b, 0},          /* TAB */  /* Keyboard Tab */
    {0x28, 0},          /* LF  */  /* Keyboard Return (Enter) */
    {0, 0},             /* VT  */
    {0, 0},             /* FF  */
    {0, 0},             /* CR  */
    {0, 0},             /* SO  */
    {0, 0},             /* SI  */
    {0, 0},             /* DLE */
    {0, 0},             /* DC1 */
    {0, 0},             /* DC2 */
    {0, 0},             /* DC3 */
    {0, 0},             /* DC4 */
    {0, 0},             /* NAK */
    {0, 0},             /* SYN */
    {0, 0},             /* ETB */
    {0, 0},             /* CAN */
    {0, 0},             /* EM  */
    {0, 0},             /* SUB */
    {0, 0},             /* ESC */
    {0, 0},             /* FS  */
    {0, 0},             /* GS  */
    {0, 0},             /* RS  */
    {0, 0},             /* US  */
    {0x2c, 0},          /*   */
    {0x1e, ASCIIMAP_MODIFIER_SHIFT},      /* ! */
    {0x1f, ASCIIMAP_MODIFIER_SHIFT},      /* " */
    {0x20, ASCIIMAP_MODIFIER_SHIFT},      /* # */
    {0x21, ASCIIMAP_MODIFIER_SHIFT},      /* $ */
    {0x22, ASCIIMAP_MODIFIER_SHIFT},      /* % */
    {0x23, ASCIIMAP_MODIFIER_SHIFT},      /* & */
    {0x24, 0},          /* ' */
    {0x25, ASCIIMAP_MODIFIER_SHIFT},      /* ( */
    {0x26, ASCIIMAP_MODIFIER_SHIFT},      /* ) */
    {0x34, ASCIIMAP_MODIFIER_SHIFT},      /* * */
    {0x33, ASCIIMAP_MODIFIER_SHIFT},      /* + */
    {0x36, 0},          /* , */
    {0x2d, 0},          /* - */
    {0x37, 0},          /* . */
    {0x38, 0},          /* / */
    {0x27, 0},          /* 0 */
    {0x1e, 0},          /* 1 */
    {0x1f, 0},          /* 2 */
    {0x20, 0},          /* 3 */
    {0x21, 0},          /* 4 */
    {0x22, 0},          /* 5 */
    {0x23, 0},          /* 6 */
    {0x24, 0},          /* 7 */
    {0x25, 0},          /* 8 */
    {0x26, 0},          /* 9 */
    {0x34, 0},      /* : */
    {0x33, ASCIIMAP_MODIFIER_SHIFT},      /* ; */
    {0x36, ASCIIMAP_MODIFIER_SHIFT},      /* < */
    {0x2d, ASCIIMAP_MODIFIER_SHIFT},          /* = */
    {0x37, ASCIIMAP_MODIFIER_SHIFT},      /* > */
    {0x38, ASCIIMAP_MODIFIER_SHIFT},      /* ? */
    {0x2f, 0},      /* @ */
    {0x04, ASCIIMAP_MODIFIER_SHIFT},      /* A */
    {0x05, ASCIIMAP_MODIFIER_SHIFT},      /* B */
    {0x06, ASCIIMAP_MODIFIER_SHIFT},      /* C */
    {0x07, ASCIIMAP_MODIFIER_SHIFT},      /* D */
    {0x08, ASCIIMAP_MODIFIER_SHIFT},      /* E */
    {0x09, ASCIIMAP_MODIFIER_SHIFT},      /* F */
    {0x0a, ASCIIMAP_MODIFIER_SHIFT},      /* G */
    {0x0b, ASCIIMAP_MODIFIER_SHIFT},      /* H */
    {0x0c, ASCIIMAP_MODIFIER_SHIFT},      /* I */
    {0x0d, ASCIIMAP_MODIFIER_SHIFT},      /* J */
    {0x0e, ASCIIMAP_MODIFIER_SHIFT},      /* K */
    {0x0f, ASCIIMAP_MODIFIER_SHIFT},      /* L */
    {0x10, ASCIIMAP_MODIFIER_SHIFT},      /* M */
    {0x11, ASCIIMAP_MODIFIER_SHIFT},      /* N */
    {0x12, ASCIIMAP_MODIFIER_SHIFT},      /* O */
    {0x13, ASCIIMAP_MODIFIER_SHIFT},      /* P */
    {0x14, ASCIIMAP_MODIFIER_SHIFT},      /* Q */
    {0x15, ASCIIMAP_MODIFIER_SHIFT},      /* R */
    {0x16, ASCIIMAP_MODIFIER_SHIFT},      /* S */
    {0x17, ASCIIMAP_MODIFIER_SHIFT},      /* T */
    {0x18, ASCIIMAP_MODIFIER_SHIFT},      /* U */
    {0x19, ASCIIMAP_MODIFIER_SHIFT},      /* V */
    {0x1a, ASCIIMAP_MODIFIER_SHIFT},      /* W */
    {0x1b, ASCIIMAP_MODIFIER_SHIFT},      /* X */
    {0x1c, ASCIIMAP_MODIFIER_SHIFT},      /* Y */
    {0x1d, ASCIIMAP_MODIFIER_SHIFT},      /* Z */
    {0x30, 0},          /* [ */
    {0x89, 0},          /* \ */
    {0x32, 0},          /* ] */
    {0x2e, 0},      /* ^ */
    {0x87, ASCIIMAP_MODIFIER_SHIFT},      /* _ */
    {0x2f, ASCIIMAP_MODIFIER_SHIFT},          /* ` */
    {0x04, 0},          /* a */
    {0x05, 0},          /* b */
    {0x06, 0},          /* c */
    {0x07, 0},          /* d */
    {0x08, 0},          /* e */
    {0x09, 0},          /* f */
    {0x0a, 0},          /* g */
    {0x0b, 0},          /* h */
    {0x0c, 0},          /* i */
    {0x0d, 0},          /* j */
    {0x0e, 0},          /* k */
    {0x0f, 0},          /* l */
    {0x10, 0},          /* m */
    {0x11, 0},          /* n */
    {0x12, 0},          /* o */
    {0x13, 0},          /* p */
    {0x14, 0},          /* q */
    {0x15, 0},          /* r */
    {0x16, 0},          /* s */
    {0x17, 0},          /* t */
    {0x18, 0},          /* u */
    {0x19, 0},          /* v */
    {0x1a, 0},          /* w */
    {0x1b, 0},          /* x */
    {0x1c, 0},          /* y */
    {0x1d, 0},          /* z */
    {0x30, ASCIIMAP_MODIFIER_SHIFT},      /* { */
    {0x89, ASCIIMAP_MODIFIER_SHIFT},      /* | */
    {0x32, ASCIIMAP_MODIFIER_SHIFT},      /* } */
    {0x2e, ASCIIMAP_MODIFIER_SHIFT},      /* ~ */
};
